# Generated by Django 3.1.4 on 2021-01-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
